services:
  api:
    container_name: shop_brain_api
    build: 
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - 8000:$APP_PORT
    restart: 'no'

  adminer:
    image: adminer
    container_name: shop_brain_adminer
    depends_on:
      - db
    ports:
      - 3000:8080
    networks:
      - shop_brain
    restart: 'no'

  db:
    restart: 'no'