services:
  api:
    container_name: shop_brain_api
    build: 
      context: .
      target: prod
    volumes:
      - .env:/app/.env
      - .env.local:/app/.env.local
    ports:
      - 80:$APP_PORT
    networks:
      - shop_brain
    restart: always
  
  db:
    container_name: shop_brain_db
    image: mariadb
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
    networks:
      - shop_brain
    restart: always

networks:
  shop_brain:

volumes:
  db_data:
    driver: local


