# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and test app

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  install-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install deps
        run: yarn install
      - name: Lint code
        run: yarn lint --max-warnings 0
      - name: Unit testing
        run: yarn test
      - name: E2E testing
        run: yarn test:e2e
      - name: Build app
        run: yarn run build
